### ISSUE TITLE
Repetition on the same wave files

### ISSUE THREAD

**Issue by wildfiremedia** [alemangui/pizzicato#31]
If the piano will need to play fast on the same notes, if I use sound.stop() when keys is release, the sound is cut off absurdly which is not right for sustain playing. How do I repeat the same wave that can overlap a bit of each tone?

While playing, how can I set the play timing back to certain time to continue from there?

**Comment by wildfiremedia** [comment]
I think the release is the solution but it's not efficient when the keys repetition happen to fast, it would still cut off the release phase. 
```
options: { path: ['./piano.wav'], release: 1 }
```

The ideal should be release phase have it own dedicated audio context that could continue playing and is not affected by keys release.

**Comment by alemangui** [comment]
I think this is a problem with the current release implementation. I agree with you - if a ```Pz.Sound``` is going back and forth ```play```and ```stop``` quickly, the release should not be cutoff.

I don't think we need a new property ```selfrelease```, I think the existing ```release``` property should behave as you need it to behave.

**Comment by wildfiremedia** [comment]
Great, I have been working on it for years and may have a few ideas to work with DIY MIDI keyboards. If we can include the option for transition parameter for other sounds say if the cars is accelerate with motor noise, the cutoff-transition will play cars' emergency braking sound.
```
options: { path: ['./piano.wav'], release: 1, cutoff-transition: ['./transition.wav']}
options: { path: ['./piano.wav'], release: 1, blend-transition: ['./transition.wav']}
```

**Comment by wildfiremedia** [comment]
Is this issue being work on?

**Comment by alemangui** [comment]
Not at the moment, I don't think I will be able to jump into this for the next couple weeks.

There are two different subjects in this issue:

1. A bug in the release property (which should be dealt with soon), and
2. A feature request to include transitions. I'm not sure when/whether this would be added. It's worth discussing about it and the potential use cases.

Let's use this issue to focus on number 1, and if needed open a new one for number 2.

**Comment by wildfiremedia** [comment]
Sure, at the moment I will need to work on it with my temporary solution.

Would it be feasible to create spare variables pianoc4-1, pianoc4-2, pianoc4-3, pianoc4-4, pianoc4-5 that:

if the pianoc4-1 is still release or have not reach the end, pianoc4-2 would start playing in fast repetition
if the pianoc4-1 and pianoc4-2 are still release or have not reach the end, pianoc4-3 would start playing in fast repetition

I guess I could this clone method but that will increase memory, is it acceptable to load/clone and unload when the wave is need to playback?

**Comment by alemangui** [comment]
It seems sub-optimal from a perf point of view, but I would have to take a look once I'm back home (abroad at the moment).

**Comment by proyb6** [comment]
Any ETA for this bug fix?

**Comment by alemangui** [comment]
### Bug fix

Here's my take on this issue:

The abrupt cut-off @wildfiremedia talked about was likely happening because the attack and release went to-and-from near zero values regardless of the fadeNode's previous state, messing up all kind of things. Kind of like this (ugly) drawing I made:

![before](https://cloud.githubusercontent.com/assets/1225929/21750031/297b8540-d5aa-11e6-948e-d7e1bd37b870.PNG)

I believe the attack and release features need to take into consideration the fadeNode's previous state:

![after](https://cloud.githubusercontent.com/assets/1225929/21750033/3509575c-d5aa-11e6-8210-d10952678990.PNG)

There were some other issues that stemmed from this: the click noise heard when disconnecting a transitioning source node, the callbacks, etc.

### Release overlap

I am not fully convinced of maintaining the release after the sound starts playing again (overlapping releases). In a real piano, each key hits its own unique string. Even if you have the piano's sustain pedal pressed, hitting multiple times the same key will 'reset' in a way the release from the previous key hit and restart it. I may be wrong of course, and I'm open to suggestions or use cases.
