### ISSUE TITLE
Same effect to multiple sounds

### ISSUE THREAD

**Issue by mdings** [alemangui/pizzicato#34]
As far as I can read from the docs, an effect can be attached to a single sound. Is it also possible to attach an effect to multiple sounds at the same time?

The compressor for example should compress multiple sound inputs. Or how does that work exactly?

**Comment by alemangui** [comment]
Sure, you can definitely use the same effect with multiple sound objects. Something like this:

```javascript
// create 2 sound objects
var guitar = new Pz.Sound(...);
var keyboard = new Pz.Sound(...);

// create a delay effect
var delay = new Pz.Effects.Delay();

// add the delay to both sounds
guitar.addEffect(delay);
keyboard.addEffect(delay);
```

After this, both sounds have the same effect. Modifying any parameters to the effect will be heard in both sounds.

**Comment by mdings** [comment]
Ok, that makes sense. Is there no way to attach an effect to an output node from the audioContext though? 
That would remove the need to add the effects to every separate channel.

**Comment by alemangui** [comment]
Yes, you can attach Pizzicato Effects to any AudioNode (https://github.com/alemangui/pizzicato#connecting-nodes-to-effects). 
```javascript
// AudioNode
var oscillator = Pizzicato.context.createOscillator();

// Pizzicato Effect
var distortion = new Pizzicato.Effects.Distortion();

// Connecting both
oscillator.connect(distortion);
```

**Comment by mdings** [comment]
So I have three Pizzicato sound file instances initiated by `new Pizzicato.Sound()`. When they are playing I want to add a flanger to the master output gain. I am doing something like below but I don't hear the effect at all. Is this the correct way of adding effects to the master gain?

`
const flanger = new Pizzicato.Effects.Flanger({
    time: 0.45,
    speed: 0.2,
    depth: 0.1,
    feedback: 0.1,
    mix: 0.5
})

const input = Pizzicato.masterGainNode
const output = Pizzication.context.createGain()

input.connect(flanger)
flanger.connect(output)
`

**Comment by JohnPaulHarold** [comment]
@mdings this sounds like you're treading similar ground as I was previously. See https://github.com/alemangui/pizzicato/issues/16 However, note that since that ticket, the Pz routing system got an update, so also see https://github.com/alemangui/pizzicato/issues/23. Disclaimer, I've not had the time to look into the routing changes as real life kicked in :-( but I think this should be in the right area for you.

**Comment by alemangui** [comment]
@mdings I would need to dive into the code, but here's a guess:

You are using ```Pizzicato.masterGainNode``` and connecting effects to it. This may not work because the masterGainNode is connected to the context.destination, and the flanger you are connecting to it (and to the output node subsequently) doesn't seem to be routed to the context's destination.

Let's say you have three different Sound objects: 
```javascript
const sound1 = new Pz.Sound();
const sound2 = new Pz.Sound();
const sound3 = new Pz.Sound();
```

and you would like to add a flanger to all three of them. The easy way would be to do this:
```javascript
sound1.addEffect(flanger);
sound2.addEffect(flanger);
sound3.addEffect(flanger);
```

Then you could toggle on and off the flanger effect by setting the mix to ```1``` and ```0``` respectively. Alternatively, you could use removeEffect and addEffect if you need to toggle the effects with more granularity across the sounds.

------------------

Now let's try a more complex way, in which we manually wire up the effects. First we would need to have the sounds [detached from the destination](https://github.com/alemangui/pizzicato#creating-a-detached-pizzicatosound-object) - we'll wire it ourselves.

```javascript
const sound1 = new Pz.Sound(source: wave,  options: { detached: true } );
const sound2 = new Pz.Sound(source: wave,  options: { detached: true } );
const sound3 = new Pz.Sound(source: wave,  options: { detached: true } );
```

Now we can create a gain node in which we can centralize the three sounds
```javascript
gainMerger = Pz.context.createGain()
```

and make the necessary connections
```javascript
// Connect sounds to gain
sound1.connect(gainMerger);
sound2.connect(gainMerger);
sound3.connect(gainMerger);

// Connect gain to flanger
gainMerger.connect(flanger)

// Connect flanger to destination
flanger.connect(Pz.context.destination)
```

For this particular case I don't see an advantage on doing this, but it may be useful if you require a more specific audio graph.
