### ISSUE TITLE
Effects blast bug

### ISSUE THREAD

**Issue by proyb6** [alemangui/pizzicato#44]
I guess this created a loopback that causes horn feedback?

[![IMG_0603.jpg](https://s29.postimg.org/l6v5lastj/IMG_0603.jpg)](https://postimg.org/image/8s8dkz1b7/)

**Comment by alemangui** [comment]
Can you prepare a working demo of this? JSFiddle or CodePen would work

**Comment by proyb6** [comment]
Try testing on Chrome with wave file on var a and a2. I don't have Internet
at home due to down time. I would only post latest tomorrow or weekend.

**Comment by proyb6** [comment]
Copy and paste the code with the 3 files of your version and pls lower the
volume to the minimum otherwise it will blast your ears


<script src="./Pizzicato.min.js"></script>
<script>
var quadrafuzz = new Pizzicato.Effects.Quadrafuzz({
lowGain: 1,
midLowGain: .2,
midHighGain: .2,
highGain: .2
});

var level = .5

function det(a) {
    return new Pizzicato.Sound("./"+a+".wav", function() {options: {
detached: true }} );
}


var a    = det("A1h");a.attack = 0;a.release = 5;
var a2   = det("A1h");a2.attack = 0;a2.release = 5;


var convolver = new Pizzicato.Effects.Convolver({
    impulse: './c.wav',
    mix: .1
}, function() {
    console.log('Convolver ready to be used.');
});


//Chains and connected to context destination

//source -> convolver -> ...
a.volume=.4
a.connect(convolver);
convolver.connect(quadrafuzz);
quadrafuzz.connect(Pz.context.destination);

//source -> quadrafuzz -> convoler -> Output
a2.volume=.4
a2.connect(quadrafuzz);
quadrafuzz.connect(convolver);
convolver.connect(Pz.context.destination);

document.onkeyup =
function(event) {
    switch(event.key) {
        case "1": a.stop();break;
        case "2": a2.stop();break;
    }
}

document.onkeypress =
function(event) {
    switch(event.key) {
        case "1": a.play();break;
        case "2": a2.play();break;

    }
}
</script>

**Comment by proyb6** [comment]
Manage to reproduce the bug?

**Comment by alemangui** [comment]
I'm out of town for the moment, but it would be much easier to see a working demo on jsfiddle than pasted code. You can add external libraries in jsfiddle by going to external ressources and pasting the cdnjs link of Pizzicato (```https://cdnjs.cloudflare.com/ajax/libs/pizzicato/0.5.1/Pizzicato.js```)

<img width="182" alt="screen shot 2017-01-22 at 9 51 17 am" src="https://cloud.githubusercontent.com/assets/1225929/22183291/6664f570-e088-11e6-9461-5f666a03807b.png">

For the external files, you can use the audio files used in pizzicato's website directly from jsfiddle, for instance:
```https://alemangui.github.io/pizzicato/audio/tremolo-guitar.m4a```
```https://alemangui.github.io/pizzicato/audio/drums.m4a```

-------------------

Nonetheless, just taking a quick glimpse at the code above, I don't think this is correct:

```javascript
function det(a) {
    return new Pizzicato.Sound("./"+a+".wav", function() {options: { detached: true }} );
}
```

You seem to be trying to send options inside a callback function? The correct way to instantiate can be found on the docs [here](https://github.com/alemangui/pizzicato#sounds-from-a-file-example) :

```javascript
var sound = new Pizzicato.Sound({ 
    source: 'file',
    options: { path: './audio/sound.wav' }
}, function() {
    console.log('sound file loaded!');
});
```

As a general tip, I would advise to manage better the callbacks. Since you are using convolvers and external sound files try to place your code and logic after in the callbacks to ensure you have all the objects ready to go.

**Comment by proyb6** [comment]
The code is just a demo example, the bug appear in the effects. Will create
a JSfiddle once I'm free.

**Comment by proyb6** [comment]
The demo was written as an example with bug on the effects. My Internet is
quite bad here.

**Comment by proyb6** [comment]
JSFiddle *Caution loud volume ahead! Turn down the volume and took off headphone before opening the link *
https://jsfiddle.net/jonuwc2n/5/

My wave files are hosted on HTTP which cannot be serve on non-secure protocol. I have use your drum as an example that will also produce the same bug:
https://alemangui.github.io/pizzicato/audio/drums.m4a

**Comment by alemangui** [comment]
Interesting stuff. Here's my take on it:

1. The sound glitch can only be heard in **Chrome**. Safari and Firefox behave well.
2. The glitch appears with or without Pizzicato. To reproduce it just use a wave shaper with a curve function and a convolver connected to each other in a loop way (https://jsfiddle.net/qv9psxuL/2/ - careful with your ears)
3. Given that this seems to be a Chrome-specific situation and that it happens independently of Pizzicato, the issue will be closed.

That said, I don't understand what you are trying to achieve - maybe you can tell me more. 

The code in the jsfiddle link loops the quadrafuzz and the convolver in this manner:
<img width="407" alt="screen shot 2017-01-27 at 4 16 08 pm" src="https://cloud.githubusercontent.com/assets/1225929/22387930/fb8f93a4-e4ab-11e6-846e-e79e860c480c.png">

Why would you want to connect the effects this way?

Regardless of whether or not a Sound object exist, this configuration will create a looping feedback in Chrome that creates the sound glitch.
