### ISSUE TITLE
Release stopped working on Firefox

### ISSUE THREAD

**Issue by midipixel** [alemangui/pizzicato#79]
I've been working on a sound design app that uses Pizzicato heavily. Release was working fine on every supported browser, but it has stopped working on Firefox 57.0.4 (64-bit). I don't know exactly when, sinceI've been developing on Chrome for a while, but perhaps it was the Quantum release?

At the moment, this is easily verifiable at [Pizzicato's own Attack/Release Demo](https://alemangui.github.io/pizzicato/#attack-release)

**Comment by alemangui** [comment]
Thanks for raising this 👍  Confirmed on my side as well with the new Firefox release. Will take a look.

**Comment by midipixel** [comment]
No problem! By the way, I ended up writing my own release method, and I wonder if you'd considered using [setTargetAtTime ](https://developer.mozilla.org/en-US/docs/Web/API/AudioParam/setTargetAtTime), instead of setValueAtTime. As MDN describes, it is "useful for decay or release portions of ADSR envelopes" and I agree! My implementation was quite simple:

```
            var envStart = Pz.context.currentTime + soundDuration - release;
            var timeConstant = parseFloat(release/3).toFixed(2);
            this.node.gain.setTargetAtTime(0, envStart, timeConstant);
```

Also, I think you'd like to check out the [app ](http://blendwave.net/beta) I'm developing with Pizzicato. It's a sound design tool for begginers. The envelope is still buggy in this version, but the other features are OK. ;)

**Comment by alemangui** [comment]
Oh I think I see the problem... The issue with this bug is calculating the "real" remaining release (or attack for that matter).

So for instance, imagine you have a sound with an attack of 1 second and a release of 1 second as well. Let's say you: 

- **a)** start the sound 
- **b)** keep it playing for 2 seconds (so now it's past the attack phase), 
- **c)** pause the sound only for 500ms (the release kicks in) and 
- **d)** play the sound again.

In step **c)** the release will kick in. However, before it is done we start playing the sound again, so now the release must stop and the attack must take over. 

The tricky part here is knowing how much time the attack should last. The *total* attack time is 1 second, but here we are at mid-release (half-way, at 500ms). In this case Pizzicato is designed to perform an attack of only 500ms as opposed to a whole second.

The same applies for the inverse case, in which the release starts mid-attack.

The way Pizzicato knows this is by checking where the ```fadeNode.gain.value``` is when the attack or release kick-in. Firefox Quantum appears to have made a regression and the ```gain.value``` is wrong, so in this case the effective release time can't be calculated.

I had raised a bug a while ago about this [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1195145). It's [parent bug](https://bugzilla.mozilla.org/show_bug.cgi?id=893020) has been reopened.

A very simple way of seeing this bug is this JSFiddle : http://jsfiddle.net/nhysww69/1/  If you open it in Chrome you'll see that the gain values are correctly printed. In Firefox they are wrong.

Unfortunately the only work-around I can think of is to remove the *effective* attack-release time for Firefox users.

**Comment by alemangui** [comment]
The Firefox-specific workaround is present on version 0.6.3.

**Comment by midipixel** [comment]
Ooooh... now I understand why you wrote the code that way! :D Just an opinion about this rationale:

> However, before it is done we start playing the sound again, so now the release must stop and the attack must take over.

The situation you describe isn't how most ADSR envelopes are implemented. On most synths and samplers, as you certainly know, once a note (or sound) is played, you can't pause it midway and then resume, reapplying the envelope in the remaining part of a sound. ADSR amplitude envelopes are usually used to shape a sound's volume based on sounds from the real world, which can't really be paused/resumed.

It's not that Pizzicato shouldn't be able to achieve what you describe, but it sure sounds like an exception, not the most common use case. So I wouldn't bother so much about it, if it meant having to deal with browser exceptions...
