### ISSUE TITLE
Audio not playing on iPhone

### ISSUE THREAD

**Issue by vonba** [alemangui/pizzicato#81]
Hi there,

I can't get the audio to start on iPhone. The file seems to load but never actually play. Could it be because of a restriction needing a click event?

Here's a very simple test - a blank page that plays a sample. It seems to work on Android but not on iPhone - tested in Safari and Chrome.
http://balthazaurus.com/audiotest

The code is essentially the same as on the demo site:

```
    <script src="Pizzicato.min.js"></script>
    <script>
        var audioTest = new Pizzicato.Sound('./Trekk-A.wav', function() {
            // Sound loaded!
            audioTest.play();
        });
    </script>
```

Many thanks.

**Comment by bptremblay** [comment]
Me too! iPhone console does not show a js exception.

**Comment by bptremblay** [comment]
This documentation suggests that no matter what you do, your app cannot play sound on an IOS device if it's not triggered by a real UI event (pressing a button). 
This means you can't write a web application that just starts playing audio. It also explains why the pizzicato demo works.
https://developer.apple.com/library/content/documentation/AudioVideo/Conceptual/Using_HTML5_Audio_Video/PlayingandSynthesizingSounds/PlayingandSynthesizingSounds.html#//apple_ref/doc/uid/TP40009523-CH6-SW5

**Comment by vonba** [comment]
My issue was that it *was* triggered by a click event, but still wouldn't play. And this restriction exists on Android as well, but on Android the test did work.

I ended up loading the audio automatically on page load and then having the play method triggered directly by the click event, and this works on both Android and iOS.

So the problem seems to be that, as far as iOS is concerned, the connection between the click event and the callback subsequently firing is lost.

**Comment by alemangui** [comment]
Hey, 

Yep, iOS can be a bit of a headache with the physical triggers needed for the web audio to start playing.

"So the problem seems to be that, as far as iOS is concerned, the connection between the click event and the callback subsequently firing is lost" that's an interesting point, and given that the loading of an external audio file is asynchronous I don't know if there's a way to circumvent it other than making sure all external files are loaded before loading the UI. Would need to look deeper.

**Comment by adrian-the-git** [comment]
It appears you just need to play *some* audio in response to a user generated event in order to "unlock" the audio and start using the APIs on iOS. I'm not sure which events count, but `click` is probably a safe bet.
```
    let context = Pizzicato.context
    let source = context.createBufferSource()
    source.buffer = context.createBuffer(1, 1, 22050)
    source.connect(context.destination)
    source.start()
```

**Comment by vonba** [comment]
@adrian-the-git I already worked around my issue by first loading all my files and then showing a play button, but your solution sounds like a good option.

**Comment by adrian-the-git** [comment]
@Aman1324 for iOS, ensure that your first call to `play` is in response to some kind of user input event, _not_ in the callback to said event provided by a web framework. If the callback is deferred in any way, iOS won't unlock the audio context.

**Comment by divineuniverse** [comment]
Hi , 

i am new to pizzicato.js , 
and i am using laptop , chrome browser , 
may i know , for file , such as ( `./sound.wav` ) , 
do i need to change any path config on .js files and/or any setting in the browser , so that to start to play a sound , ?!
( now i cannot hear any ) , 

THANKS for any replies and help , !! , : )
