### ISSUE TITLE
Group sounds

### ISSUE THREAD

**Issue by nascent** [alemangui/pizzicato#88]
Hi,

Great product, best I've found so far and from a musician is even better but I was wondering whether more than one group can be used at a time, in a similar manner to how an audio console might work such that a Group can be part of another Group.

Cheers

**Comment by nascent** [comment]
It definitely does what is on the pack and is the *only* solution that allows a fully custom multitrack player that abstracts the detail away from getting the job done.

About Groups, I meant being able to put groups in group, aka sub-groups so for example I have drums in one group, percussion in another and a drum machine (all mp3s) but each group is fed by single tracks for kick, snare etc., so if I could have a single fader for all 3 groups I could mute them all at once.

Best regards.

**Comment by alemangui** [comment]
The only way of achieving this would be to manually make the connections between the groups by [creating an audio graph](https://github.com/alemangui/pizzicato#using-pizzicato-objects-in-a-web-audio-graph).

So for instance, if you have three groups that you want to connect to a single node you can do so manually using the ```connect``` function. It would look something like this:

```
group1.connect(node)
group2.connect(node)
group3.connect(node)
```

Unfortunately if you are planning on using detached sounds you won't be able to use groups. Since your application seems a bit more complex in terms of audio graph I would advise to use Pizzicato [detached souds](https://github.com/alemangui/pizzicato#creating-a-detached-pizzicatosound-object) and grouping them manually to better fit your needs.

The section on [using Pizzicato objects in a web audio graph](https://github.com/alemangui/pizzicato#using-pizzicato-objects-in-a-web-audio-graph) should be useful for this scenario.
